openapi: 3.0.3
info:
  title: F1 Tracker - Races
  description: F1 Tracker - Races
  version: 0.1.0
servers:
  - url: 'https://f1tracker.chaserz.com/api/races'
paths:
  /years:
    get:
      description: Gets a list of all years with races
      responses:
        200:
          description: A list of years with races
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
  /years/{year}:
    get:
      description: A list of all races for a year
      responses:
        200:
          description: A list of race names and IDs for a year
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
  /{id}:
    get:
      description: Gets the details of a specific race
      parameters:
        - in: path
          name: id
          required: true
          schema:
            $ref: 'components.yaml#/components/schemas/raceId'
      responses:
        200:
          description: Details of a race
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/Race'
    put:
      description: Create a new race
      parameters:
        - in: path
          name: id
          required: true
          schema:
            $ref: 'components.yaml#/components/schemas/raceId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'components.yaml#/components/schemas/Race'
      responses:
        200:
          description: Successfully created race
        500:
          description: Problem creating race
    post:
      description: Update an existing race
      parameters:
        - in: path
          name: id
          required: true
          schema:
            $ref: 'components.yaml#/components/schemas/raceId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'components.yaml#/components/schemas/Race'
      responses:
        200:
          description: Successfully created race
        500:
          description: Problem creating race
