openapi: 3.0.3
info:
  title: F1 Tracker - Tracks
  description: F1 Tracker - Tracks
  version: 0.1.0
servers:
  - url: 'https://f1tracker.chaserz.com/api/tracks'
paths:
  /:
    get:
      description: Gets a list of track names and IDs
      responses:
        200:
          description: A list of track names and IDs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
  /{id}:
    get:
      description: Gets the details of a specific track
      parameters:
        - in: path
          name: id
          required: true
          schema:
            $ref: 'components.yaml#/components/schemas/trackId'
      responses:
        200:
          description: Details of a track
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/Track'
    put:
      description: Create a new track
      parameters:
        - in: path
          name: id
          required: true
          schema:
            $ref: 'components.yaml#/components/schemas/trackId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'components.yaml#/components/schemas/Track'
      responses:
        200:
          description: Successfully created track
        500:
          description: Problem creating track
    post:
      description: Update an existing track
      parameters:
        - in: path
          name: id
          required: true
          schema:
            $ref: 'components.yaml#/components/schemas/trackId'
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'components.yaml#/components/schemas/Track'
      responses:
        200:
          description: Successfully created track
        500:
          description: Problem creating track

